#!/usr/bin/env bash

# 26.11.2020 - Paul Czechowski - paul.czechowski@gmail.com 
# ========================================================
# Import sequence files into Qiime 2.

# safety settings 
#   "-u" makes it an error to reference a non-existent environment variable 
#   "pipefail" makes things like misspeled-command raise errors.

set -eu
set -o pipefail


# Adjust base paths
# -----------------
if [[ "$HOSTNAME" != "Pauls-MacBook-Pro.local" ]] && [[ "$HOSTNAME" != "macmini-fastpost-1.staff.uod.otago.ac.nz" ]]; then
    
    # adjust terminal colours
    bold=$(tput bold)
    normal=$(tput sgr0)

    # location message 
    printf "${bold}$(date):${normal} Execution on remote is not implemnted...\n"

elif [[ "$HOSTNAME" == "Pauls-MacBook-Pro.local" ]]  || [[ "$HOSTNAME" == "macmini-fastpost-1.staff.uod.otago.ac.nz" ]]; then
    bold=$(tput bold)
    normal=$(tput sgr0)
    printf "${bold}$(date):${normal} Execution on local...\n"
    trpth="/Users/paul/Documents/OU_eDNA"
    cores="2"
fi

# barcode file generated by `/Users/paul/Documents/OU_eDNA/200901_scripts/201028_sample_matadata_managment.R` on or after 1-12-2020
barcodes="/201126_preprocessing/metadata/200_cutadapt_barcode_input.txt" 

# input file array - 12S
inpth[1]="/201120_sequence_data/OG6304-211308098/FASTQ_Generation_2020-11-19_01_33_21Z-343990651/6304-P1-0-1_L001-ds.21f7e23247f540d4b3dfe0004841c2b5/6304-P1-0-1_S1_L001_R1_001.fastq.gz"

# Run import script - adjust `i` starting number! 
# -----------------------------------------------
for ((i=1;i<=1;i++)); do

    # diagnostic message
    printf "${bold}$(date):${normal} Demultiplexing \"$(basename "$trpth"/"${inpth[$i]}")\"...\n"
    
    # creating_partial_output file name
    outdir="$trpth"/201126_preprocessing/cutadapt
    namest="$outdir"/"$(basename "$trpth"/"${inpth[$i]}" .fastq.gz)"
    
    # for debugging only
    # echo "$namest"
    
    # step through barcode file
    while IFS=" " read -r smplnm fwdbc revbc
      do
        
        # generate output file name
        outfile="$namest"__"$smplnm".fastq.gz

        # for debugging only
        # echo "$outfile"
        
        # reverse complement trailing adapter
        revbc_rc=$(echo $revbc | grep '^[atcg]' | rev | tr atcg tagc)
        
        # echo "$revbc"
        # echo "$revbc_rc"

          # call import only if output file isn't already there
          if [ ! -f "$outfile" ]; then
            
            cutadapt -g "$fwdbc"..."$revbc_rc" -o "$outfile" "$trpth""${inpth[$i]}"  --discard-untrimmed --revcomp -e 0

          else
     
            # diagnostic message
            printf "${bold}$(date):${normal} Import available for \"$(basename "$trpth"/"${inpth[$i]}")\", skipping.\n"
   
          fi
    
    done < "$trpth"/"$barcodes"

done
