# Fiordland project 03-12-2020
#
# Create Qiime manifest
#   - using files in `/Users/paul/Documents/OU_eDNA/201126_preprocessing/cutadapt`
#   - using object used for demultiplexing information `/Users/paul/Documents/OU_eDNA/201028_Robjects/201028_sample_managment__demux_table.Rdata`
#   - possibly using  metadata combined: `/Users/paul/Documents/OU_eDNA/201028_Robjects/201028_sample_managment__big_table.Rdata`
#
# manifest example: 
# 
# sample-id     absolute-filepath
# sample-1      $PWD/some/filepath/sample1_R1.fastq
# sample-2      $PWD/some/filepath/sample2_R1.fastq

# Environment
# ===========
install.packages("tidyverse")
library("tidyverse")

rm(list = ls())

# Read in stored objects
# =======================

load("/workdir/pc683/OU_eDNA/201028_Robjects/201028_sample_managment__demux_table.Rdata")
load("/workdir/pc683/OU_eDNA/201028_Robjects/201028_sample_managment__big_table.Rdata")

# Read in fastq files generated by `/Users/paul/Documents/OU_eDNA/200901_scripts/300_conda_cutadapt_demultiplex.sh`
#  and put them in tibble for further manipulation
manifest <- as_tibble( fqpaths <- list.files("/workdir/pc683/OU_eDNA/201126_preprocessing/cutadapt", pattern = "\\.fastq.gz$")) %>%
  rename("absolute-filepath" = "value")

# Format manifest
# ================

# add Qiime-conform sample-id column
manifest <- manifest %>% mutate( `sample-id` = sub('_', '-',  sub('.fastq.gz', '',  sub('.*\\__', '', `absolute-filepath`))))

# add paths to manifest  
manifest <- manifest %>% mutate( "absolute-filepath" = paste0("/workdir/pc683/OU_eDNA/201126_preprocessing/cutadapt/", `absolute-filepath`))

manifest <- manifest %>% select("sample-id",  "absolute-filepath") %>% mutate( direction = "forward")

# Write manifest file
# ===================
write_excel_csv(manifest, "/workdir/pc683/OU_eDNA/201126_preprocessing/metadata/400_create_qiime_manifest__manifest.txt")

